version: '3.6'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMPQ_URL: 'ampq;//rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: rabbitmqctl status || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
  conversion_cron:
    build:
      context: ../../aplicaciones-nube
      dockerfile: ./services/conversion_cron/Dockerfile