version: '3.6'

volumes:
  files:
    external: true
services:
  worker:
    build: 
      context: ../../aplicaciones-nube
      dockerfile: ./worker/Dockerfile
    volumes:
    - files:/files
    ports:
    - 5004:5004
  message-queue-process:
    build:
      context: ../../aplicaciones-nube
      dockerfile: ./worker/message-queue/Dockerfile
    command: "python /worker/message-queue/consumer-process-queue.py"
    volumes:
    - files:/files
