version: '3.6'

volumes:
  files:
    external: true
services:
  worker:
    build: 
      context: ../../aplicaciones-nube
      dockerfile: ./worker/Dockerfile
    volumes:
    - files:/mnt/nfs_clientshare
    ports:
    - 5004:5004

