version: '3.6'

volumes:
  files:
    external: true
services:
  
  api:
    build: 
      context: ../../aplicaciones-nube
      dockerfile: ./api/Dockerfile
    ports:
    - 5002:5002
    volumes:
      - files:/files

